#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonoDroid.DialogSample.Resource", IsApplication=true)]

namespace MonoDroid.DialogSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int list_dialog_items = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int multilist_dialog_items = 2130968577;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int AlertDialogButton = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int CustomViewDialogButton = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int DatePickerDialogButton = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int FragmentDialogsButton = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int ListDialogButton = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int MultiChoiceDialogButton = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int NumberPickerDialogButton = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int YesNoDialogButton = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int fragment_container = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int numberPicker = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int password = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int username = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DialogFragment_Contents = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NumberPickerDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Page_Dialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Page_DialogFragment = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int bomb_dialog_title = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int dialog_cancel = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int dialog_date = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int dialog_main_screen = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int dialog_number = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int dialog_ok = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int dialog_signal = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int knigts_dialog_title = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int list_dialog_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int multi_choice_dialog_title = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int multi_dialog_cancel = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int no = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int number_dialog_title = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int yes = 2131034125;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
